//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoberModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.MeetingFormatTypes = new HashSet<MeetingFormatType>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<short> DayId { get; set; }
        public Nullable<System.DateTime> MeetingTime { get; set; }
        public Nullable<bool> ClosedToPublic { get; set; }
        public Nullable<bool> WheelChair { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Zip { get; set; }
        public string Place { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public short Type { get; set; }
        public string MeetingName { get; set; }
        public string WebsiteSource { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
    
        public virtual MeetingType MeetingType { get; set; }
        public virtual ICollection<MeetingFormatType> MeetingFormatTypes { get; set; }
    }
}
