//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoberModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingType
    {
        public MeetingType()
        {
            this.Meetings = new HashSet<Meeting>();
        }
    
        public short TypeId { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Meeting> Meetings { get; set; }
    }
}
